#!/bin/bash
echo "Running: docker-compose -f ../Docker/docker-compose.yml exec workspace bash -c 'cd web && composer $*'"
docker-compose -f ../Docker/docker-compose.yml exec workspace bash -c "cd web && composer $*"